# Generated by Django 5.0.4 on 2024-04-12 18:04

import utils.hex_uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='fire_id',
            field=models.CharField(default=utils.hex_uuid.get_uuid_hexed, max_length=128, null=True),
        ),
    ]
