# Generated by Django 5.0.4 on 2024-04-12 18:05

from django.db import migrations, models
from utils.hex_uuid import get_uuid_hexed


def gen_uuid(apps, schema_editor):
    Lib_model = apps.get_model("lms", "LibraryUser")
    for row in Lib_model.objects.all():
        row.fire_id = get_uuid_hexed()
        row.save(update_fields=["fire_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_libraryuser_fire_id_null'),
    ]

    operations = [
        migrations.RunPython(gen_uuid,
                             reverse_code=migrations.RunPython.noop),
    ]
