# Generated by Django 5.0.4 on 2024-04-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_fireid_to_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.FileField(blank=True, upload_to='book-images'),
        ),
    ]
