# Generated by Django 5.0.4 on 2024-04-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_book_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lms.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='book_history',
            field=models.ManyToManyField(through='lms.ReadingHistory', to='lms.book'),
        ),
        migrations.AddConstraint(
            model_name='readinghistory',
            constraint=models.UniqueConstraint(fields=('user', 'book', 'start_date'), name='unique_history'),
        ),
    ]
