# Generated by Django 5.0.4 on 2024-04-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_readinghistory_libraryuser_book_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryuser",
            name="book_history",
            field=models.ManyToManyField(
                related_name="book_history", through="lms.ReadingHistory", to="lms.book"
            ),
        ),
    ]
